wordpress:
  build: .
  ports:
    - 80:80
  volumes:
    - .:/wordpress
  privileged: true
  environment:
    URL: 'http://localhost'
    DB_USER: root
    DB_PASSWORD: ''
    DB_NAME: wp_publishing_test
    DB_HOST: mysql:3306
    WP_ENV: staging
    WP_HOME: 'http://localhost'
    WP_SITEURL: 'http://localhost/wp'
    AUTH_KEY: "sde34£%34df@@*%566dfgrgerttrertwerkvcx;blkrtlkweroeowerryPo"
    SECURE_AUTH_KEY: '-s+IAu|O]w0ySeH= Hc=G|[Pgr+zFq.X#&|{us3u%yY@cz]_jby1Cn+)6DL.F='
    LOGGED_IN_KEY: 't)|uj(,yX#CKkw.#|Mm;:VnNNH*jc.,8%lm+eO=N!c1j&h|Imxs(Zu^G*:~]0+AI'
    NONCE_KEY: 'N|S*V(;{c^,^|ea=g-ivw;uMd>_Jj%SDfc4}(i&<^;(/(a))oB{gK2z#^]W_N~z*'
    AUTH_SALT: 'O|S*V(;{c^,^|ea=g-ivw;uMd>_Jj%SDfc4}(i&!c1j&h|Imxs(Zu^G*:~]0+AI'
    SECURE_AUTH_SALT: '(]fE60-d-D]k%:.RkXHTDfD-=XZ%KR 2Wu^ZN|R|Hnd:0oo4}LxYTsZS>od#8{ '
    LOGGED_IN_SALT: 'sy%|)TabZ,|-;046;+Smc>JW~;~5A}Mv(v|.-XJSy.8(VqhY.Iafv_>7yuQHM~f'
    NONCE_SALT: '5C@XK}%9TKH_U8(Vu@izg!8305Yq+p~IOlcx@bFpA9eTTw:>c-y#^PDNOVA}'
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    DISABLE_WP_CRON: true
    SERVER_NAME: localhost
    WHITELIST_IPS: ${WHITELIST_IPS}
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PORT: ${SMTP_PORT}
    SMTP_USER: ${SMTP_USER}
    SMTP_PASS: ${SMTP_PASS}
    SMTP_USE_STARTTLS: ${SMTP_USE_STARTTLS}
    SMTP_USE_SSL: ${SMTP_USE_SSL}
  links:
    - mysql
mysql:
  image: orchardup/mysql
  environment:
    MYSQL_DATABASE: wp_publishing_test
